# Generated by Django 5.0.2 on 2026-02-24 15:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('HCII', 'Health Center II'), ('HCIII', 'Health Center III'), ('HCIV', 'Health Center IV'), ('HOSPITAL', 'Hospital'), ('REFERRAL', 'Referral Hospital')], max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_capacity_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited Capacity'), ('FULL', 'Full'), ('EMERGENCY_ONLY', 'Emergency Only')], default='AVAILABLE', max_length=20)),
                ('current_active_referrals', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(default=50)),
                ('specialties', models.TextField(help_text='Comma-separated specialties: general,pediatrics,maternity,surgery')),
                ('is_operational', models.BooleanField(default=True)),
                ('operating_hours', models.CharField(default='24/7', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='hospitals_latitud_0ad327_idx'), models.Index(fields=['emergency_capacity_status'], name='hospitals_emergen_b3ea35_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('VHT', 'VHT Member'), ('HOSPITAL', 'Hospital Staff'), ('ADMIN', 'Administrator'), ('VIEWER', 'Viewer')], default='VHT', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('vht_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('hospital_code', models.CharField(blank=True, help_text='Hospital ID code entered during registration', max_length=50, null=True)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('primary_language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Swahili')], default='en', max_length=5)),
                ('voice_feedback_enabled', models.BooleanField(default=True)),
                ('is_active_vht', models.BooleanField(default=True)),
                ('photo', models.CharField(blank=True, help_text='Photo URL or path', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.hospital')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TRIAGE', 'Triage Performed'), ('REFERRAL', 'Referral Created'), ('ALERT', 'Emergency Alert Sent'), ('AI_DECISION', 'AI Decision Made'), ('VALIDATION', 'AI Validation'), ('USER_ACTION', 'User Action')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'), models.Index(fields=['action_type'], name='audit_logs_action__168beb_idx')],
            },
        ),
    ]
