# Generated by Django 6.0.2 on 2026-03-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('region', models.CharField(help_text='Central, Eastern, Northern, Western', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('village_count', models.IntegerField(default=0, help_text='Number of villages in this district')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='districts_name_961bdc_idx'), models.Index(fields=['region'], name='districts_region_0d1941_idx')],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='core.district')),
            ],
            options={
                'db_table': 'villages',
                'ordering': ['district', 'name'],
                'indexes': [models.Index(fields=['district', 'name'], name='villages_distric_20cf22_idx'), models.Index(fields=['latitude', 'longitude'], name='villages_latitud_736d8d_idx')],
                'unique_together': {('name', 'district')},
            },
        ),
    ]
