# Generated by Django 6.0.2 on 2026-03-04 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hospital_sub_county_district_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REFERRAL_ACCEPTED', 'Referral Accepted'), ('REFERRAL_UPDATED', 'Referral Updated'), ('PATIENT_ARRIVED', 'Patient Arrived'), ('COMPLETED', 'Treatment Completed'), ('ALERT', 'Emergency Alert'), ('INFO', 'Information')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Additional data like referral_id, patient_id')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx')],
            },
        ),
    ]
