# Generated by Django 6.0.2 on 2026-03-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VHTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_monitoring_enabled', models.BooleanField(default=True, help_text='Enable continuous AI monitoring for health signals')),
                ('auto_triage_enabled', models.BooleanField(default=True, help_text='Allow AI to automatically triage patients based on symptoms')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Receive push notifications for urgent cases and referral updates')),
                ('high_alert_threshold', models.IntegerField(default=80, help_text='AI confidence score threshold (%) that triggers urgent alerts')),
                ('auto_refresh_interval', models.IntegerField(default=30, help_text='Dashboard auto-refresh interval in seconds (0 = disabled)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'VHT'}, on_delete=django.db.models.deletion.CASCADE, related_name='vht_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VHT Settings',
                'verbose_name_plural': 'VHT Settings',
                'db_table': 'vht_settings',
            },
        ),
    ]
