# Generated by Django 5.0.2 on 2026-02-24 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vht_code', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.CharField(help_text="Can be '8mo' or '42' years", max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('triage_level', models.CharField(choices=[('STABLE', 'Stable'), ('MODERATE', 'Moderate'), ('HIGH_RISK', 'High Risk'), ('URGENT', 'Urgent')], default='STABLE', max_length=20)),
                ('triage_score', models.IntegerField(default=0, help_text='1-10 scale')),
                ('last_triage_confidence', models.FloatField(default=0.0, help_text='AI confidence 0-1')),
                ('village', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='JSON or comma-separated')),
                ('allergies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.CharField(blank=True, help_text='Photo URL or path', max_length=500, null=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('INTAKE', 'Voice Intake'), ('TRIAGE', 'Triage Assessment'), ('FOLLOWUP', 'Follow-up'), ('REFERRAL', 'Referral'), ('TREATMENT', 'Treatment Update')], max_length=50)),
                ('notes', models.TextField()),
                ('triage_score_at_time', models.IntegerField(blank=True, null=True)),
                ('symptoms_at_time', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patients.patient')),
                ('vht_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient histories',
                'db_table': 'patient_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=200)),
                ('name_luganda', models.CharField(blank=True, max_length=200)),
                ('name_swahili', models.CharField(blank=True, max_length=200)),
                ('severity', models.IntegerField(default=5, help_text='1-10 scale')),
                ('duration', models.CharField(blank=True, help_text="e.g., '3 days'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('detected_by_ai', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('voice_recording', models.FileField(blank=True, null=True, upload_to='symptom_audio/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='patients.patient')),
            ],
            options={
                'db_table': 'symptoms',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['vht_code'], name='patients_vht_cod_4cb8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['triage_level'], name='patients_triage__a3dbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['-last_visit'], name='patients_last_vi_15bcf9_idx'),
        ),
    ]
