# Generated by Django 6.0.2 on 2026-03-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, help_text="Patient's district (from village or manual entry)", max_length=100),
        ),
    ]
