# Generated by Django 5.0.2 on 2026-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='case_audio/')),
                ('audio_duration', models.FloatField(blank=True, help_text='Seconds', null=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_time', models.FloatField(blank=True, help_text='Seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('transcription', models.TextField(blank=True)),
                ('translation_confidence', models.FloatField(blank=True, null=True)),
                ('triage_result', models.JSONField(default=dict)),
                ('validation_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'case_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
