# Generated by Django 6.0.2 on 2026-03-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
        ('referrals', '0002_alter_referral_guideline_citation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDecisionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('TRIAGE_SCORE', 'Triage Score Adjusted'), ('REFERRAL_HOSPITAL', 'Referral Hospital Changed'), ('INCORRECT_DECISION', 'Flagged as Incorrect')], max_length=30)),
                ('original_value', models.JSONField(help_text='Original AI decision/value before override')),
                ('new_value', models.JSONField(help_text='New value after VHT override')),
                ('reason', models.TextField(help_text="VHT's explanation for the override")),
                ('clinical_notes', models.TextField(blank=True, help_text='Additional clinical context or observations')),
                ('was_correct_override', models.BooleanField(blank=True, help_text='Later validation: was this override justified?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='ai_engine.casesubmission')),
                ('overridden_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_overrides', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='referrals.referral')),
            ],
            options={
                'db_table': 'ai_decision_overrides',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['override_type'], name='ai_decision_overrid_8c8566_idx'), models.Index(fields=['overridden_by'], name='ai_decision_overrid_5662c2_idx')],
            },
        ),
    ]
