# Generated by Django 5.0.2 on 2026-02-24 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50, unique=True)),
                ('urgency_level', models.CharField(choices=[('STABLE', 'Stable'), ('MODERATE', 'Moderate'), ('HIGH_RISK', 'High Risk'), ('URGENT', 'Urgent')], max_length=20)),
                ('triage_score', models.IntegerField(help_text='1-10 scale')),
                ('confidence_score', models.FloatField(help_text='AI confidence 0-1')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('estimated_travel_time', models.IntegerField(help_text='Minutes')),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('primary_condition', models.CharField(max_length=200)),
                ('symptoms_summary', models.TextField()),
                ('recommended_specialty', models.CharField(blank=True, max_length=100)),
                ('first_aid_instructions', models.JSONField(default=list)),
                ('ai_reasoning', models.TextField(blank=True, help_text="AI's reasoning for this referral")),
                ('guideline_citation', models.CharField(blank=True, max_length=500)),
                ('validation_passed', models.BooleanField(default=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('hospital_notified', models.BooleanField(default=False)),
                ('hospital_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('REFERRAL', 'Emergency Referral'), ('CRITICAL', 'Critical Patient'), ('FOLLOWUP', 'Follow-up Required'), ('COMMUNITY', 'Community Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('message_content', models.TextField()),
                ('sms_provider', models.CharField(blank=True, max_length=50)),
                ('sms_id', models.CharField(blank=True, max_length=200)),
                ('sent_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='referrals.referral')),
            ],
            options={
                'db_table': 'emergency_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code'], name='referrals_referra_3eadcc_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='referrals_status_135a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['urgency_level'], name='referrals_urgency_34a16e_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['-created_at'], name='referrals_created_c89401_idx'),
        ),
    ]
