# Generated by Django 6.0.2 on 2026-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='guideline_citation',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
